a=int(input("enter first number:"))
b=int(input("enter second number:"))
print("addition=",(a+b))
print("substraction=",(a-b))
print("divition=",(a/b))
print("modulus=",(a%b))
print("multiplication=",(a*b))
